name: "2 [pull/pr] Initiate workflow"

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  check-storybook-folder-changes:
    name: Check storybook folder changes
    if: ${{ ! startsWith(github.ref, 'refs/tags') }}
    uses: ./.github/workflows/dev_on_workflow_check_folder_change.yml
    with:
      folder: |
        .storybook/**
        src/**
  yarn-chromatic:
    needs: [check-storybook-folder-changes]
    uses: ./.github/workflows/dev_on_workflow_chromatic.yml
    if: needs.check-storybook-folder-changes.outputs.folder_changed == 'true'
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
